apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    service: elasticsearch
spec:
  clusterIP: None
  ports:
    - name: serving
      port: 9200
    - name: node-to-node
      port: 9300
  selector:
    service: elasticsearch
