apiVersion: v1
kind: Service
metadata:
  name: janusgraph-service-lb
spec:
  type: LoadBalancer
  selector:
    app: janusgraph
  ports:
    - name: gremlin-server-websocket
      protocol: TCP
      port: 8182
      targetPort: 8182
